// <auto-generated />
using System;
using DuncanLaud.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuncanLaud.Infrastructure.Analytics.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260329185450_InitialAnalyticsSchema")]
    partial class InitialAnalyticsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuncanLaud.Analytics.Entities.ApiEvent", b =>
                {
                    b.Property<long>("ApiEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApiEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<int?>("RequestBytes")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseBytes")
                        .HasColumnType("int");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint");

                    b.HasKey("ApiEventId");

                    b.HasIndex("Endpoint", "CreatedAt")
                        .HasDatabaseName("IX_api_events_endpoint");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("IX_api_events_session");

                    b.ToTable("api_events", "analytics");
                });

            modelBuilder.Entity("DuncanLaud.Analytics.Entities.PageEvent", b =>
                {
                    b.Property<long>("PageEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PageEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("GET");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint");

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UrlQuery")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("PageEventId");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("IX_page_events_session");

                    b.HasIndex("UrlPath", "CreatedAt")
                        .HasDatabaseName("IX_page_events_path");

                    b.ToTable("page_events", "analytics");
                });

            modelBuilder.Entity("DuncanLaud.Analytics.Entities.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<int>("EventCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SessionEnd")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgentRaw")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("SessionId");

                    b.HasIndex("IpHash", "SessionStart")
                        .HasDatabaseName("IX_sessions_ip_hash");

                    b.ToTable("sessions", "analytics");
                });

            modelBuilder.Entity("DuncanLaud.Analytics.Entities.ApiEvent", b =>
                {
                    b.HasOne("DuncanLaud.Analytics.Entities.Session", "Session")
                        .WithMany("ApiEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DuncanLaud.Analytics.Entities.PageEvent", b =>
                {
                    b.HasOne("DuncanLaud.Analytics.Entities.Session", "Session")
                        .WithMany("PageEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DuncanLaud.Analytics.Entities.Session", b =>
                {
                    b.Navigation("ApiEvents");

                    b.Navigation("PageEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
