on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
        
    - name: Get .NET information
      run: dotnet --info
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,18.0)'
        vs-prerelease: false

    - name: Checkout repository
      id: checkout_repo
      uses: actions/checkout@v3

    - name: Clean .NET cache
      id: clean_dotnet_cache
      shell: pwsh
      run: |
        dotnet clean .\DuncanLaud.WebUI.sln
        dotnet nuget locals all --clear

    - name: Install NuGet packages
      id: install_nuget_packages
      shell: pwsh
      run: |
        nuget restore .\DuncanLaud.WebUI.sln

    - name: Build solution
      id: build_solution
      shell: pwsh
      run: |
        msbuild .\DuncanLaud.WebUI.sln
          
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: https://win5025.site4now.net:8172/msdeploy.axd?site=developerlando-001-site1
        port: 8172
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        dry-run: true