name: Deploy to FTP Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Upgrade & Update
        run: sudo apt-get update

      - name: Upgrade & Update
        run: sudo apt-get upgrade

      - name: Install FTP client
        run: sudo apt-get install -y lftp
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish GithubWorkflowApp/GithubWorkflowApp.csproj --configuration Release --output ./publish --runtime win-x86 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false

      - name: Deploy via FTP
        run: |
          lftp -c "set ftp:ssl-allow no;
                   open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
                   mirror --parallel=10 -R --verbose ./publish /" || true
        env:
          FTP_USERNAME: ${{ secrets.ftp_username }}
          FTP_PASSWORD: ${{ secrets.ftp_password }}
          FTP_SERVER: ${{ secrets.SERVER_COMPUTER_NAME }}
