name: Deploy to FTP Server Stage
on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, reopened]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Upgrade & Update
        run: sudo apt-get update && sudo apt-get upgrade
        
      - name: Install FTP client
        run: sudo apt-get install -y lftp
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish DuncanLaud.WebUI/DuncanLaud.WebUI.csproj --configuration Release --output ./publish --runtime win-x86 --self-contained false -p:PublishTrimmed=false -p:PublishSingleFile=false

      - name: Deploy via FTP
        run: |
          lftp -c "set ftp:ssl-allow no;
                   set net:timeout 600;
                   set net:max-retries 2;
                   set log:enabled true;
                   open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
                   mirror --parallel=10 -R --verbose ./publish /"
        env:
          FTP_USERNAME: ${{ secrets.STAGE_USERNAME }}
          FTP_PASSWORD: ${{ secrets.STAGE_PASSWORD }}
          FTP_SERVER: ${{ secrets.STAGE_SERVER }}
